name: "CI: Build & Test"

on:
  workflow_call:
    inputs:
      build_version:
        required: true
        type: string
    secrets:
      SNYK_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  quick-build:
    runs-on: ubuntu-latest
    outputs:
      imagename: ${{ env.imagename }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      -
        name: Prepare
        id: prep
        run: |
          IMAGENAME="ttl.sh/$(uuidgen | tr '[:upper:]' '[:lower:]'):3h"
          echo "imagename=${IMAGENAME}" >> $GITHUB_ENV
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3
      -
        name: Build and export
        id: build
        uses: docker/build-push-action@5176d81f87c23d6fc96624dfdbcd9f3830bbe445 # v6
        with:
          context: .
          push: true
          tags: ${{ env.imagename }}

  snyk-scan:
    needs: [quick-build]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      -
        name: Pull docker image
        id: load
        run: |
          docker pull ${{needs.quick-build.outputs.imagename}}
      -
        name: Test the image with Snyk for high-severity vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{needs.quick-build.outputs.imagename}}
          args: --file=Dockerfile --severity-threshold=high
